[build]

command = 'npm run build'

publish = 'build/'

[functions]

directory = 'functions/'

node_bundler = "esbuild"

[[redirects]]
from="/movie/*"
to="http://wishmovie.netlify.app/:splat"
status=200